# Generated by Django 4.2 on 2025-12-10 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hr', 'HR'), ('tech', 'Tech'), ('apt', 'Aptitude'), ('beh', 'Behavioral')], default='hr', max_length=20)),
                ('difficulty', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('source', models.CharField(default='llm', max_length=50)),
                ('signature', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='general', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='in_progress', max_length=20)),
                ('current_index', models.IntegerField(default=0)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('answer_text', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviewapp.generatedquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviewapp.interviewsession')),
            ],
            options={
                'unique_together': {('session', 'index')},
            },
        ),
    ]
