# Generated by Django 4.2 on 2025-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0002_interviewsession_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
