# Generated by Django 4.2 on 2025-12-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0005_remove_interviewsession_total_questions_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='improvement_tips',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
