# Generated by Django 4.2 on 2025-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0006_answer_improvement_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_answers/'),
        ),
    ]
